### ISSUE TITLE
Get docker with testmud and webmud3 up and running

### ISSUE THREAD

**Issue by myonara** [myonara/webmud3#21]
# Task List
- [x] Create autark docker file for webmud3 
*  docker build --no-cache --progress=plain -f unitopia_homemud.dockerfile -t webmud3:testmud .

- [x] Create autark docker file for webmud3 
* docker build --no-cache --progress=plain -f wm3.dockerfile -t myonara/webmud3:wm3test .

- [ ] Create and test windows compose file

# Results
### Dockerfile wm3.dockerfile

```
FROM node:20.12.2 AS ng-build-stage

# docker build --progress=plain -f wm3.dockerfile -t wm3test .
# docker build --no-cache --progress=plain -f wm3.dockerfile -t wm3test .

RUN apt-get update -y \
 && apt upgrade -y \
 && apt-get install -y --no-install-recommends bash git \
 && npm install --location=global @angular/cli \
 && git clone -b develop https://github.com/mystiker/webmud3.git \
 && cd webmud3/frontend \
 && npm install \
 && npm run build \
 && cd ../backend \
 && npm install \
 && npm run build  \
 && cd .. \
 && npm install \
 && npm run postbuild

# Setze die Umgebungsvariable PORT
ENV PORT=5000

# Exponiere den Port, auf dem die Anwendung läuft
EXPOSE 5000

# Starte die Anwendung
CMD ["node", "main.js"]

```

### Dockerfile unitopia_homemd.deockerfiee:
```
FROM node:20.12.2 AS ng-build-stage

# docker build --progress=plain -f wm3.dockerfile -t wm3test .
# docker build --no-cache --progress=plain -f wm3.dockerfile -t wm3test .

RUN apt-get update -y \
 && apt upgrade -y \
 && apt-get install -y --no-install-recommends bash git \
 && npm install --location=global @angular/cli \
 && git clone -b develop https://github.com/mystiker/webmud3.git \
 && cd webmud3/frontend \
 && npm install \
 && npm run build \
 && cd ../backend \
 && npm install \
 && npm run build  \
 && cd .. \
 && npm install \
 && npm run postbuild

# Setze die Umgebungsvariable PORT
ENV PORT=5000

# Exponiere den Port, auf dem die Anwendung läuft
EXPOSE 5000

# Starte die Anwendung
CMD ["node", "main.js"]

```
